"""added units

Revision ID: 21bc9cf9d56b
Revises: 3a27ee26a6e7
Create Date: 2025-10-30 01:22:03.213349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bc9cf9d56b'
down_revision = '3a27ee26a6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
