"""added units

Revision ID: 3a27ee26a6e7
Revises: 3da3e3fb5577
Create Date: 2025-10-30 01:21:21.296207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a27ee26a6e7'
down_revision = '3da3e3fb5577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
