"""added quiz fiddgiddiffcuity

Revision ID: 5e9e908b66e8
Revises: 34121f66319e
Create Date: 2025-11-13 20:07:08.144261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9e908b66e8'
down_revision = '34121f66319e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), server_default='2', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
