"""grade

Revision ID: 6748de54588e
Revises: 819ed1b7bee0
Create Date: 2025-10-31 10:48:06.608724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6748de54588e'
down_revision = '819ed1b7bee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), server_default='6', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
