"""grade

Revision ID: 819ed1b7bee0
Revises: ca7229e9ad31
Create Date: 2025-10-31 10:44:21.632484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819ed1b7bee0'
down_revision = 'ca7229e9ad31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
