"""your message

Revision ID: 95c6122e9ec8
Revises: 61b1a31aed7e
Create Date: 2025-11-17 16:24:41.230406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c6122e9ec8'
down_revision = '61b1a31aed7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.drop_column('unit')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
