"""model modified for integrity constraints

Revision ID: ddb770337528
Revises: c4c74ac1b8e9
Create Date: 2025-11-02 20:39:33.594145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb770337528'
down_revision = 'c4c74ac1b8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('question_quiz_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('question_quiz_id_fkey'), 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
