"""added elo table

Revision ID: f772553afbac
Revises: 21bc9cf9d56b
Create Date: 2025-10-30 18:39:56.158198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f772553afbac'
down_revision = '21bc9cf9d56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), server_default='1000', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elo')
    # ### end Alembic commands ###
